import os
import sys
import random
import logging
import json
import csv
import re
import pdb
import argparse
from typing import List, Tuple, Dict, Any

import torch
from tqdm import tqdm
from datasets import load_dataset
from transformers import AutoModelForCausalLM, AutoTokenizer

# Add project root directory
sys.path.append("..")
from customed_model.customed_qwen_model import CustomedQwenForCausalLM

# Set logging level
logging.basicConfig(level=logging.INFO)

# Set random seed
random.seed(112)

def generate_response(model, tokenizer, prompt: str, candidate_layers: List[int], top_n: int):
    """
    Generate a response based on the input prompt and return activation keys for each layer and the generated answer.

    Args:
        model: Model object.
        tokenizer: Tokenizer object.
        prompt: Input text prompt.
        candidate_layers: List of candidate early exit layers.
        top_n: Number of top-N activated neurons.

    Returns:
        hidden_embed: Dictionary recording decoded text for each layer.
        answer: Final answer generated by the model.
        activate_keys_gate, activate_keys_fwd_up, activate_keys_fwd_down, activate_keys_q, activate_keys_k,
        activate_keys_v, activate_keys_o, layer_keys: Various activation keys and layer info.
    """
    inputs = tokenizer(prompt, return_tensors="pt").to("cuda")
    (hidden_states, next_input_ids, 
     activate_keys_gate, activate_keys_fwd_up, activate_keys_fwd_down,
     activate_keys_q, activate_keys_k, activate_keys_v,
     activate_keys_o, layer_keys) = model.generate(
        input_ids=inputs["input_ids"],
        attention_mask=inputs["attention_mask"],
        candidate_premature_layers=candidate_layers,
        top_n = top_n,
        largest = False,
        max_new_tokens=1,
        do_sample=False  # Use greedy decoding
    )

    return (None, None, 
            activate_keys_gate, activate_keys_fwd_up, activate_keys_fwd_down,
            activate_keys_q, activate_keys_k, activate_keys_v, 
            activate_keys_o, layer_keys)


def get_common_elements(activation_sets: List[Dict]) -> Dict:
    """
    Extract the common set of activated values for each key from multiple activation dictionaries.

    Args:
        activation_sets (List[Dict]): List of activation dictionaries from multiple samples.

    Returns:
        common_elements (Dict): Common activated values for each key.
    """
    common_elements = {}
    for key in activation_sets[0].keys():
        if all(key in d for d in activation_sets):
            arrays = [d[key] for d in activation_sets]
            common_elements[key] = set.intersection(*map(set, arrays))
    return common_elements


def main():
    # Use argparse to parse command-line arguments
    parser = argparse.ArgumentParser(description="Process math_cot datasets with Qwen model")
    parser.add_argument("--model", type=str, required=True, help="Path to the model")
    parser.add_argument("--dataset", type=str, default="math_cot_1", 
                        help="Dataset name (math_cot_1 to math_cot_10)")
    parser.add_argument("--split", type=str, default="train", help="Dataset split (e.g., 'train')")
    parser.add_argument("--samples", type=int, default=10, help="Number of samples to process")
    parser.add_argument("--top_n", type=int, default=16000, help="Top-N neurons to consider")
    
    args = parser.parse_args()
    
    # Model and dataset related configuration
    MODEL_NAME = args.model
    DATASET_NAME = args.dataset
    DATASET_PATH = f'LLaMA-Factory/data/mixed/{DATASET_NAME}.jsonl'  # Construct path based on dataset parameter
    split_name = args.split
    sample_count = args.samples
    top_n = args.top_n

    # Load tokenizer and model (automatically map to device)
    tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
    model = CustomedQwenForCausalLM.from_pretrained(MODEL_NAME, 
                                                   device_map="auto",
                                                   attn_implementation="flash_attention_2",
                                                   torch_dtype=torch.bfloat16)

    # Load the specified split of the dataset
    try:
        dataset = load_dataset('json', data_files=DATASET_PATH)[split_name]
    except Exception as e:
        logging.error(f"Failed to load dataset: {e}")
        return

    # Construct prompt for each Q&A pair (customize format if needed)
    logging.info(f"Dataset sample: {dataset[0]}")
    prompts = [f"{record['text']}" for record in dataset]

    if sample_count > len(prompts):
        logging.warning("Sample size exceeds total dataset size, using all samples.")
        sample_count = len(prompts)

    sampled_prompts = random.sample(prompts, sample_count)
    candidate_layers = list(range(32))

    # Containers for storing various activation information
    activate_keys_set_gate = []
    activate_keys_set_fwd_up = []
    activate_keys_set_fwd_down = []
    activate_keys_set_q = []
    activate_keys_set_k = []
    activate_keys_set_v = []

    failure_count = 0

    # Iterate through all sampled prompts and generate responses and activation info
    for prompt in tqdm(sampled_prompts, desc="Processing prompts"):
        try:
            (_, answer, 
             act_gate, act_fwd_up, act_fwd_down, 
             act_q, act_k, act_v, 
             _, _) = generate_response(model, tokenizer, prompt, candidate_layers, top_n)
            activate_keys_set_gate.append(act_gate)
            activate_keys_set_fwd_up.append(act_fwd_up)
            activate_keys_set_fwd_down.append(act_fwd_down)
            activate_keys_set_q.append(act_q)
            activate_keys_set_k.append(act_k)
            activate_keys_set_v.append(act_v)
        except Exception as e:
            failure_count += 1
            logging.error(f"Error processing prompt: {e}")

    if not activate_keys_set_fwd_up:
        logging.error("All prompts failed to process, exiting.")
        return

    # Extract common elements for each type of activation key
    common_elements_gate = get_common_elements(activate_keys_set_gate)
    common_elements_fwd_up = get_common_elements(activate_keys_set_fwd_up)
    common_elements_fwd_down = get_common_elements(activate_keys_set_fwd_down)
    common_elements_q = get_common_elements(activate_keys_set_q)
    common_elements_k = get_common_elements(activate_keys_set_k)
    common_elements_v = get_common_elements(activate_keys_set_v)

    # Construct output file path
    successful_count = sample_count - failure_count
    output_file_path = os.path.join(
        "./output_neurons",
        "qwen",
        DATASET_NAME.replace("/", "_"),
        f"math/{top_n}/{successful_count}.txt"
    )
    os.makedirs(os.path.dirname(output_file_path), exist_ok=True)

    # Write common activation elements to output file
    try:
        with open(output_file_path, 'w', encoding='utf-8') as file:
            file.write(str(common_elements_gate) + '\n')
            file.write(str(common_elements_fwd_up) + '\n')
            file.write(str(common_elements_fwd_down) + '\n')
            file.write(str(common_elements_q) + '\n')
            file.write(str(common_elements_k) + '\n')
            file.write(str(common_elements_v) + '\n')
        logging.info(f"Results saved to {output_file_path}")
    except Exception as e:
        logging.error(f"Failed to save output file: {e}")
        
    # Write input arguments to a parameter file
    args_file_path = os.path.join(os.path.dirname(output_file_path), "input_arguments.txt")
    try:
        with open(args_file_path, 'w', encoding='utf-8') as f:
            f.write("Input Arguments:\n")
            f.write(f"MODEL_NAME: {MODEL_NAME}\n")
            f.write(f"DATASET_PATH: {DATASET_PATH}\n")
            f.write(f"DATASET_NAME: {DATASET_NAME}\n")
            f.write(f"split_name: {split_name}\n")
            f.write(f"sample_count: {sample_count}\n")
            f.write(f"top_n: {top_n}\n")
        logging.info(f"Input arguments saved to {args_file_path}")
    except Exception as e:
        logging.error(f"Failed to save input arguments file: {e}")
    

if __name__ == "__main__":
    main()