import os
import sys
import random
import logging
import json
import csv
import re
import pdb
from typing import List, Tuple, Dict, Any

import torch
from tqdm import tqdm
from datasets import load_dataset
from transformers import AutoModelForCausalLM, AutoTokenizer

# Add project root directory
sys.path.append("..")
from customed_model.customed_llama_model import CustomedLlamaForCausalLM

# Set logging level
logging.basicConfig(level=logging.INFO)

# Fix random seed
random.seed(112)

def generate_response(model, tokenizer, prompt: str, candidate_layers: List[int], top_n: int):
    """
    Generate a response based on the input prompt and return activation keys and the generated answer.

    Args:
        model: Model object.
        prompt: Input text prompt.
        candidate_layers: List of candidate early exit layers.

    Returns:
        hidden_embed: Dictionary recording decoded text for each layer.
        answer: Final answer generated by the model.
        activate_keys_gate, activate_keys_fwd_up, activate_keys_fwd_down, activate_keys_q, activate_keys_k,
        activate_keys_v, activate_keys_o, layer_keys: Various activation keys and layer information.
    """
    inputs = tokenizer(prompt, return_tensors="pt").to("cuda")
    (hidden_states, next_input_ids, 
     activate_keys_gate, activate_keys_fwd_up, activate_keys_fwd_down,
     activate_keys_q, activate_keys_k, activate_keys_v,
     activate_keys_o, layer_keys) = model.generate(
        input_ids=inputs["input_ids"],
        attention_mask=inputs["attention_mask"],
        candidate_premature_layers=candidate_layers,
        top_n = top_n,
        largest = False,
        max_new_tokens=1,
        do_sample=False  # Use greedy decoding
    )

    return (None, None, 
            activate_keys_gate, activate_keys_fwd_up, activate_keys_fwd_down,
            activate_keys_q, activate_keys_k, activate_keys_v, 
            activate_keys_o, layer_keys)


def get_common_elements(activation_sets: List[Dict]) -> Dict:
    """
    Extract the common activated values for each key from multiple activation dictionaries.

    Args:
        activation_sets (List[Dict]): List of activation dictionaries from multiple samples.

    Returns:
        common_elements (Dict): Dictionary of common activated values for each key.
    """
    common_elements = {}
    for key in activation_sets[0].keys():
        if all(key in d for d in activation_sets):
            arrays = [d[key] for d in activation_sets]
            common_elements[key] = set.intersection(*map(set, arrays))
    return common_elements


def main(argv):
    if len(argv) < 4:
        logging.error("Please provide 4 arguments: model path, dataset split name (e.g., 'train'), sample count, and top_n.")
        return
    
    # Model and dataset configuration
    MODEL_NAME = argv[0]
    DATASET_NAME = 'iamtarun/python_code_instructions_18k_alpaca'
    split_name = argv[1]
    sample_count = int(argv[2])
    top_n = int(argv[3])

    # Load tokenizer and model (automatically map to device)
    tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
    model = CustomedLlamaForCausalLM.from_pretrained(MODEL_NAME, device_map="auto")

    # Load the specified split of the MetaMathQA dataset
    try:
        dataset = load_dataset(DATASET_NAME, split=split_name)
    except Exception as e:
        logging.error(f"Failed to load dataset: {e}")
        return

    # Construct prompt for each Q&A pair (customize format if needed)
    prompts = [record['prompt'] for record in dataset]

    if sample_count > len(prompts):
        logging.warning("Sample count exceeds dataset size. Using all samples.")
        sample_count = len(prompts)

    sampled_prompts = random.sample(prompts, sample_count)
    candidate_layers = list(range(32))

    # Containers for storing activation information
    activate_keys_set_gate = []
    activate_keys_set_fwd_up = []
    activate_keys_set_fwd_down = []
    activate_keys_set_q = []
    activate_keys_set_k = []
    activate_keys_set_v = []

    failure_count = 0

    # Generate response and activation info for each prompt
    for prompt in tqdm(sampled_prompts, desc="Processing prompts"):
        try:
            (_, answer, 
             act_gate, act_fwd_up, act_fwd_down, 
             act_q, act_k, act_v, 
             _, _) = generate_response(model, tokenizer, prompt, candidate_layers, top_n)
            activate_keys_set_gate.append(act_gate)
            activate_keys_set_fwd_up.append(act_fwd_up)
            activate_keys_set_fwd_down.append(act_fwd_down)
            activate_keys_set_q.append(act_q)
            activate_keys_set_k.append(act_k)
            activate_keys_set_v.append(act_v)
        except Exception as e:
            failure_count += 1
            logging.error(f"Error processing prompt: {e}")

    if not activate_keys_set_fwd_up:
        logging.error("All prompts failed. Exiting.")
        return

    # Extract common activation values for each type
    common_elements_gate = get_common_elements(activate_keys_set_gate)
    common_elements_fwd_up = get_common_elements(activate_keys_set_fwd_up)
    common_elements_fwd_down = get_common_elements(activate_keys_set_fwd_down)
    common_elements_q = get_common_elements(activate_keys_set_q)
    common_elements_k = get_common_elements(activate_keys_set_k)
    common_elements_v = get_common_elements(activate_keys_set_v)

    # Construct output file path
    successful_count = sample_count - failure_count
    output_file_path = os.path.join(
        "./output_neurons",
        MODEL_NAME.replace("/", "_"),
        DATASET_NAME.replace("/", "_"),
        f"code/{top_n}/{successful_count}.txt"
    )
    os.makedirs(os.path.dirname(output_file_path), exist_ok=True)

    # Write common activation values to output file
    try:
        with open(output_file_path, 'w', encoding='utf-8') as file:
            file.write(str(common_elements_gate) + '\n')
            file.write(str(common_elements_fwd_up) + '\n')
            file.write(str(common_elements_fwd_down) + '\n')
            file.write(str(common_elements_q) + '\n')
            file.write(str(common_elements_k) + '\n')
            file.write(str(common_elements_v) + '\n')
        logging.info(f"Results saved to {output_file_path}")
    except Exception as e:
        logging.error(f"Failed to save file: {e}")


if __name__ == "__main__":
    main(sys.argv[1:])