import os
import sys
import random
import logging
import json
import csv
import re
import pdb
from dataclasses import field, dataclass
from typing import Optional, Any, List, Dict, Set

import torch
from tqdm import tqdm
from transformers import AutoTokenizer
from rouge_score import rouge_scorer
from datasets import load_dataset

# Add project root directory
sys.path.append("..")
from customed_model.customed_llama_model import CustomedLlamaForCausalLM

# Set logging level
logging.basicConfig(level=logging.INFO)

# Set random seed
# random.seed(112)

def generate_response(model, tokenizer, prompt: str, candidate_layers: List[int], top_n: int):
    """
    Generate a response based on the input prompt and return activation keys and the generated answer.

    Args:
        model: Model object.
        prompt: Input text prompt.
        candidate_layers: List of candidate early exit layers.

    Returns:
        hidden_embed: Dictionary recording decoded text for each layer.
        answer: Final answer generated by the model.
        activate_keys_gate, activate_keys_fwd_up, activate_keys_fwd_down, activate_keys_q, activate_keys_k,
        activate_keys_v, activate_keys_o, layer_keys: Various activation keys and layer information.
    """
    inputs = tokenizer(prompt, return_tensors="pt").to("cuda")
    (hidden_states, next_input_ids, 
     activate_keys_gate, activate_keys_fwd_up, activate_keys_fwd_down,
     activate_keys_q, activate_keys_k, activate_keys_v,
     activate_keys_o, layer_keys) = model.generate(
        input_ids=inputs["input_ids"],
        attention_mask=inputs["attention_mask"],
        candidate_premature_layers=candidate_layers,
        top_n = top_n,
        largest = True,
        max_new_tokens=1,
        do_sample=False  # Use greedy decoding
    )

    return (None, None, 
            activate_keys_gate, activate_keys_fwd_up, activate_keys_fwd_down,
            activate_keys_q, activate_keys_k, activate_keys_v, 
            activate_keys_o, layer_keys)


def get_common_elements(activation_sets: List[Dict]) -> Dict:
    """
    For a list of dictionaries containing activation keys, compute the common elements for each key across all dictionaries.

    Args:
        activation_sets: List of dictionaries containing activation keys.

    Returns:
        common_elements_dict: Dictionary where the key is the activation key name, and the value is the intersection of arrays for that key across all dictionaries.
    """
    common_elements_dict = {}
    if not activation_sets:
        return common_elements_dict

    # Use all keys from the first dictionary
    for key in activation_sets[0].keys():
        # Only process keys that exist in all dictionaries
        if all(key in activation for activation in activation_sets):
            arrays = [activation[key] for activation in activation_sets]
            # Compute intersection
            common_elements = set.intersection(*map(set, arrays))
            common_elements_dict[key] = common_elements
    return common_elements_dict


def main(args):
    """
    Main function:
    1. Read prompts from a text file (randomly sample a specified number).
    2. For each prompt, call generate_response to get activation key data for each layer.
    3. Compute the common elements of each type of activation key and write the results to an output file.
    """
    if len(args) < 4:
        logging.error("Please provide 4 arguments: file identifier, model path, number of samples, and top_n.")
        sys.exit(1)

    file_identifier = args[0]
    MODEL_NAME = args[1]
    sample_size = int(args[2])
    top_n = int(args[3])
    input_file_path = os.path.join("./corpus_all", f"{file_identifier}.txt")
    
    # Load tokenizer and model
    tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
    model = CustomedLlamaForCausalLM.from_pretrained(MODEL_NAME, 
                                                     device_map="auto",
                                                     attn_implementation="eager",
                                                     torch_dtype=torch.bfloat16)
    logging.info(f"Loaded model type: {type(model)}")

    # Read and sample prompts
    with open(input_file_path, 'r') as file:
        lines = [line.strip() for line in file.readlines()]
    sampled_prompts = random.sample(lines, sample_size)

    # Construct candidate early exit layers (0~31)
    candidate_layers = list(range(32))

    # Containers for storing activation key data
    activate_keys_set_gate = []
    activate_keys_set_fwd_up = []
    activate_keys_set_fwd_down = []
    activate_keys_set_q = []
    activate_keys_set_k = []
    activate_keys_set_v = []

    failure_count = 0

    # Generate response and collect activation key data for each prompt
    for prompt in tqdm(sampled_prompts, desc="Processing prompts"):
        try:
            (hidden_embed, answer, act_keys_gate, 
             act_keys_fwd_up, act_keys_fwd_down,
             act_keys_q, act_keys_k, act_keys_v,
             _, _) = generate_response(model, tokenizer, prompt, candidate_layers, top_n)
            activate_keys_set_gate.append(act_keys_gate)
            activate_keys_set_fwd_up.append(act_keys_fwd_up)
            activate_keys_set_fwd_down.append(act_keys_fwd_down)
            activate_keys_set_q.append(act_keys_q)
            activate_keys_set_k.append(act_keys_k)
            activate_keys_set_v.append(act_keys_v)
        except Exception as e:
            failure_count += 1
            logging.error(f"Error processing prompt: {e}")

    # Exit if all prompts failed
    if not activate_keys_set_fwd_up:
        logging.error("All prompts failed. Exiting.")
        return

    # Compute common elements for each activation type
    common_elements_gate = get_common_elements(activate_keys_set_gate)
    common_elements_fwd_up = get_common_elements(activate_keys_set_fwd_up)
    common_elements_fwd_down = get_common_elements(activate_keys_set_fwd_down)
    common_elements_q = get_common_elements(activate_keys_set_q)
    common_elements_k = get_common_elements(activate_keys_set_k)
    common_elements_v = get_common_elements(activate_keys_set_v)

    # Construct output directory and file path
    successful_count = sample_size - failure_count
    output_file_path = os.path.join(
        "./output_neurons",
        "llama",
        f"{file_identifier}/{top_n}/{successful_count}.txt"
    )
    os.makedirs(os.path.dirname(output_file_path), exist_ok=True)

    # Write results
    try:
        with open(output_file_path, 'w', encoding='utf-8') as file:
            file.write(str(common_elements_gate) + '\n')
            file.write(str(common_elements_fwd_up) + '\n')
            file.write(str(common_elements_fwd_down) + '\n')
            file.write(str(common_elements_q) + '\n')
            file.write(str(common_elements_k) + '\n')
            file.write(str(common_elements_v) + '\n')
        logging.info(f"Results written to {output_file_path}")
    except Exception as e:
        logging.error(f"Failed to write output file: {e}")
        
    # Write input arguments to parameter file
    args_file_path = os.path.join(os.path.dirname(output_file_path), "input_arguments.txt")
    try:
        with open(args_file_path, 'w', encoding='utf-8') as f:
            f.write("Input Arguments:\n")
            f.write(f"MODEL_NAME: {MODEL_NAME}\n")
            f.write(f"DATASET_NAME: {input_file_path}\n")
            f.write(f"sample_count: {sample_size}\n")
            f.write(f"top_n: {top_n}\n")
        logging.info(f"Input arguments saved to {args_file_path}")
    except Exception as e:
        logging.error(f"Failed to save input arguments file: {e}")


if __name__ == "__main__":
    main(sys.argv[1:])